name: pltLib
channels:
  - jmbertoncelli 
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - chardet=4.0.0
  - cryptography=42.0.5
  - exceptiongroup=1.2.0
  - iniconfig=1.1.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.13
  - packaging=23.2
  - pip=23.3.1
  - pluggy=1.0.0
  - pycparser=2.21
  - pytest=7.4.0
  - python=3.8.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tomli=2.0.1
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - dpath==1.5.0
      - idna==3.6
      - inflection==0.5.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - streamsets
      - urllib3==2.2.1
